import type { HotItem, PlatformKey } from "./types";

/**
 * 演示数据：当实时接口不可用时兜底展示，保证页面始终有内容。
 * url 均指向对应平台的搜索结果页。
 */
export const FALLBACK: Record<PlatformKey, HotItem[]> = {
  baidu: [
    { title: "国产大模型发布新一代多模态版本", hot: "1435万", url: "https://www.baidu.com/s?wd=%E5%9B%BD%E4%BA%A7%E5%A4%A7%E6%A8%A1%E5%9E%8B%E6%96%B0%E7%89%88" },
    { title: "春节档电影票房刷新影史纪录", hot: "1288万", url: "https://www.baidu.com/s?wd=%E6%98%A5%E8%8A%82%E6%A1%A3%E7%94%B5%E5%BD%B1%E7%A5%A8%E6%88%BF" },
    { title: "多地迎来今冬最强降雪天气", hot: "1021万", url: "https://www.baidu.com/s?wd=%E4%BB%8A%E5%86%AC%E6%9C%80%E5%BC%BA%E9%99%8D%E9%9B%AA" },
    { title: "新能源车冬季续航实测公布", hot: "864万", url: "https://www.baidu.com/s?wd=%E6%96%B0%E8%83%BD%E6%BA%90%E8%BD%A6%E5%86%AC%E5%AD%A3%E7%BB%AD%E8%88%AA" },
    { title: "春晚节目单首次联排曝光", hot: "798万", url: "https://www.baidu.com/s?wd=%E6%98%A5%E6%99%9A%E8%8A%82%E7%9B%AE%E5%8D%95" },
    { title: "年轻人流行起'反向消费'新潮流", hot: "663万", url: "https://www.baidu.com/s?wd=%E5%8F%8D%E5%90%91%E6%B6%88%E8%B4%B9" },
    { title: "新款折叠屏手机开售引发抢购", hot: "592万", url: "https://www.baidu.com/s?wd=%E6%96%B0%E6%AC%BE%E6%8A%98%E5%8F%A0%E5%B1%8F%E6%89%8B%E6%9C%BA" },
    { title: "文旅部公布冬季冰雪游热门城市", hot: "501万", url: "https://www.baidu.com/s?wd=%E5%86%AC%E5%AD%A3%E5%86%B0%E9%9B%AA%E6%B8%B8%E7%83%AD%E9%97%A8%E5%9F%8E%E5%B8%82" },
    { title: "国产科幻电影启动全球发行", hot: "468万", url: "https://www.baidu.com/s?wd=%E5%9B%BD%E4%BA%A7%E7%A7%91%E5%B9%BB%E7%94%B5%E5%BD%B1" },
    { title: "春运首日火车票今日开售", hot: "432万", url: "https://www.baidu.com/s?wd=%E6%98%A5%E8%BF%90%E7%81%AB%E8%BD%A6%E7%A5%A8%E5%BC%80%E5%94%AE" },
    { title: "知名游戏厂商宣布新作定档", hot: "389万", url: "https://www.baidu.com/s?wd=%E6%B8%B8%E6%88%8F%E6%96%B0%E4%BD%9C%E5%AE%9A%E6%A1%A3" },
    { title: "医保谈判结果公布多款新药入保", hot: "355万", url: "https://www.baidu.com/s?wd=%E5%8C%BB%E4%BF%9D%E8%B0%88%E5%88%A4%E7%BB%93%E6%9E%9C" },
  ],
  weibo: [
    { title: "顶流官宣恋情引爆热搜", hot: "1023万", url: "https://s.weibo.com/weibo?q=%E5%AE%98%E5%AE%A3%E6%81%8B%E6%83%85" },
    { title: "考研成绩今日公布", hot: "876万", url: "https://s.weibo.com/weibo?q=%E8%80%83%E7%A0%94%E6%88%90%E7%BB%A9%E5%85%AC%E5%B8%83" },
    { title: "哈尔滨冰雪大世界正式开园", hot: "742万", url: "https://s.weibo.com/weibo?q=%E5%93%88%E5%B0%94%E6%BB%A8%E5%86%B0%E9%9B%AA%E5%A4%A7%E4%B8%96%E7%95%8C" },
    { title: "某热播剧大结局观众意难平", hot: "698万", url: "https://s.weibo.com/weibo?q=%E7%83%AD%E6%92%AD%E5%89%A7%E5%A4%A7%E7%BB%93%E5%B1%80" },
    { title: "演唱会门票二次开售秒空", hot: "613万", url: "https://s.weibo.com/weibo?q=%E6%BC%94%E5%94%B1%E4%BC%9A%E9%97%A8%E7%A5%A8" },
    { title: "明星回应争议事件", hot: "566万", url: "https://s.weibo.com/weibo?q=%E6%98%8E%E6%98%9F%E5%9B%9E%E5%BA%94%E4%BA%89%E8%AE%AE" },
    { title: "新综艺阵容官宣", hot: "501万", url: "https://s.weibo.com/weibo?q=%E6%96%B0%E7%BB%BC%E8%89%BA%E9%98%B5%E5%AE%B9" },
    { title: "网友晒出自家雪人创意大赛", hot: "447万", url: "https://s.weibo.com/weibo?q=%E5%A0%86%E9%9B%AA%E4%BA%BA%E5%A4%A7%E8%B5%9B" },
    { title: "跨年晚会官宣首批嘉宾", hot: "389万", url: "https://s.weibo.com/weibo?q=%E8%B7%A8%E5%B9%B4%E6%99%9A%E4%BC%9A%E5%98%89%E5%AE%BE" },
    { title: "宠物橘猫表情包走红网络", hot: "302万", url: "https://s.weibo.com/weibo?q=%E6%A9%98%E7%8C%AB%E8%A1%A8%E6%83%85%E5%8C%85" },
    { title: "专家解读呼吸道疾病高发季", hot: "271万", url: "https://s.weibo.com/weibo?q=%E5%91%BC%E5%90%B8%E9%81%93%E7%96%BE%E7%97%85" },
    { title: "00后整顿职场新话题", hot: "238万", url: "https://s.weibo.com/weibo?q=00%E5%90%8E%E6%95%B4%E9%A1%BF%E8%81%8C%E5%9C%BA" },
  ],
  bilibili: [
    { title: "年度百大UP主评选结果揭晓", hot: "89万+", url: "https://search.bilibili.com/all?keyword=%E7%99%BE%E5%A4%A7UP%E4%B8%BB" },
    { title: "新番开播首集口碑炸裂", hot: "76万+", url: "https://search.bilibili.com/all?keyword=%E6%96%B0%E7%95%AA%E5%BC%80%E6%92%AD" },
    { title: "国产独立游戏发布实机演示", hot: "68万+", url: "https://search.bilibili.com/all?keyword=%E7%8B%AC%E7%AB%8B%E6%B8%B8%E6%88%8F%E5%AE%9E%E6%9C%BA" },
    { title: "手工耿新发明上线", hot: "59万+", url: "https://search.bilibili.com/all?keyword=%E6%89%8B%E5%B7%A5%E8%80%BF" },
    { title: "冰上运动合集播放量破亿", hot: "47万+", url: "https://search.bilibili.com/all?keyword=%E5%86%B0%E4%B8%8A%E8%BF%90%E5%8A%A8" },
    { title: "鬼畜区年度金曲盘点", hot: "41万+", url: "https://search.bilibili.com/all?keyword=%E9%AC%BC%E7%95%9C%E9%87%91%E6%9B%B2" },
    { title: "新人UP主一周涨粉百万", hot: "36万+", url: "https://search.bilibili.com/all?keyword=%E6%96%B0%E4%BA%BAUP%E4%B8%BB" },
    { title: "纪录片《雪原》上线", hot: "31万+", url: "https://search.bilibili.com/all?keyword=%E9%9B%AA%E5%8E%9F%E7%BA%AA%E5%BD%95%E7%89%87" },
    { title: "游戏新春版本更新预告", hot: "28万+", url: "https://search.bilibili.com/all?keyword=%E6%B8%B8%E6%88%8F%E6%96%B0%E6%98%A5%E7%89%88%E6%9C%AC" },
    { title: "科技区大佬拆解新款芯片", hot: "24万+", url: "https://search.bilibili.com/all?keyword=%E6%8B%86%E8%A7%A3%E8%8A%AF%E7%89%87" },
    { title: "跨年晚会舞台cut合集", hot: "19万+", url: "https://search.bilibili.com/all?keyword=%E8%B7%A8%E5%B9%B4%E8%88%9E%E5%8F%B0" },
    { title: "虚拟主播演唱会回放", hot: "15万+", url: "https://search.bilibili.com/all?keyword=%E8%99%9A%E6%8B%9F%E4%B8%BB%E6%92%AD%E6%BC%94%E5%94%B1%E4%BC%9A" },
  ],
  zhihu: [
    { title: "如何评价新发布的多模态大模型？", hot: "1280万热度", url: "https://www.zhihu.com/search?type=content&q=%E5%A4%9A%E6%A8%A1%E6%80%81%E5%A4%A7%E6%A8%A1%E5%9E%8B" },
    { title: "为什么年轻人开始过'无消费周末'？", hot: "986万热度", url: "https://www.zhihu.com/search?type=content&q=%E6%97%A0%E6%B6%88%E8%B4%B9%E5%91%A8%E6%9C%92" },
    { title: "东北旅游爆火背后的原因是什么？", hot: "872万热度", url: "https://www.zhihu.com/search?type=content&q=%E4%B8%9C%E5%8C%97%E6%97%85%E6%B8%B8%E7%88%86%E7%81%AB" },
    { title: "考研失败后如何规划人生？", hot: "754万热度", url: "https://www.zhihu.com/search?type=content&q=%E8%80%83%E7%A0%94%E5%A4%B1%E8%B4%A5%E4%BA%BA%E7%94%9F%E8%A7%84%E5%88%92" },
    { title: "如何看待新能源车冬季续航打折？", hot: "689万热度", url: "https://www.zhihu.com/search?type=content&q=%E6%96%B0%E8%83%BD%E6%BA%90%E8%BD%A6%E7%BB%AD%E8%88%AA" },
    { title: "普通人如何抓住AI浪潮？", hot: "611万热度", url: "https://www.zhihu.com/search?type=content&q=%E6%99%AE%E9%80%9A%E4%BA%BAAI%E6%B5%AA%E6%BD%AE" },
    { title: "有哪些值得推荐的冬季旅行地？", hot: "532万热度", url: "https://www.zhihu.com/search?type=content&q=%E5%86%AC%E5%AD%A3%E6%97%85%E8%A1%8C%E5%9C%B0" },
    { title: "为什么电影院春节档年年爆满？", hot: "477万热度", url: "https://www.zhihu.com/search?type=content&q=%E6%98%A5%E8%8A%82%E6%A1%A3%E7%94%B5%E5%BD%B1" },
    { title: "大城市的通勤幸福感从何而来？", hot: "399万热度", url: "https://www.zhihu.com/search?type=content&q=%E9%80%9A%E5%8B%A4%E5%B9%B8%E7%A6%8F%E6%84%9F" },
    { title: "如何看待'反向留学'现象？", hot: "345万热度", url: "https://www.zhihu.com/search?type=content&q=%E5%8F%8D%E5%90%91%E7%95%99%E5%AD%A6" },
    { title: "编程入门学哪门语言最合适？", hot: "312万热度", url: "https://www.zhihu.com/search?type=content&q=%E7%BC%96%E7%A8%8B%E5%85%A5%E9%97%A8%E8%AF%AD%E8%A8%80" },
    { title: "为什么南方冬天比北方更冷？", hot: "276万热度", url: "https://www.zhihu.com/search?type=content&q=%E5%8D%97%E6%96%B9%E5%86%AC%E5%A4%A9%E6%9B%B4%E5%86%B7" },
  ],
  douyin: [
    { title: "#冰雪变装挑战", hot: "1568万", url: "https://www.douyin.com/search/%E5%86%B0%E9%9B%AA%E5%8F%98%E8%A3%85%E6%8C%91%E6%88%98" },
    { title: "#城市冬日漫游指南", hot: "1211万", url: "https://www.douyin.com/search/%E5%9F%8E%E5%B8%82%E5%86%AC%E6%97%A5%E6%BC%AB%E6%B8%B8" },
    { title: "#一人食火锅新吃法", hot: "986万", url: "https://www.douyin.com/search/%E4%B8%80%E4%BA%BA%E9%A3%9F%E7%81%AB%E9%94%85" },
    { title: "#AI写真火了", hot: "874万", url: "https://www.douyin.com/search/AI%E5%86%99%E7%9C%9F" },
    { title: "#宠物第一视角vlog", hot: "762万", url: "https://www.douyin.com/search/%E5%AE%A0%E7%89%A9%E7%AC%AC%E4%B8%80%E8%A7%86%E8%A7%92" },
    { title: "#滑雪新手教程", hot: "655万", url: "https://www.douyin.com/search/%E6%BB%91%E9%9B%AA%E6%96%B0%E6%89%8B%E6%95%99%E7%A8%8B" },
    { title: "#跨年烟花夜拍", hot: "578万", url: "https://www.douyin.com/search/%E8%B7%A8%E5%B9%B4%E7%83%9F%E8%8A%B1" },
    { title: "#街头偶遇随机搭子", hot: "489万", url: "https://www.douyin.com/search/%E8%A1%97%E5%A4%B4%E5%81%B6%E9%81%87" },
    { title: "#北方冬天的快乐", hot: "402万", url: "https://www.douyin.com/search/%E5%8C%97%E6%96%B9%E5%86%AC%E5%A4%A9" },
    { title: "#收纳整理新思路", hot: "366万", url: "https://www.douyin.com/search/%E6%94%B6%E7%BA%B3%E6%95%B4%E7%90%86" },
    { title: "#幼儿园可爱瞬间", hot: "318万", url: "https://www.douyin.com/search/%E5%B9%BC%E5%84%BF%E5%9B%AD%E5%8F%AF%E7%88%B1%E7%9E%AC%E9%97%B4" },
    { title: "#考研上岸vlog", hot: "274万", url: "https://www.douyin.com/search/%E8%80%83%E7%A0%94%E4%B8%8A%E5%B2%B8" },
  ],
  google: [
    { title: "Gemini update", hot: "2M+", url: "https://www.google.com/search?q=Gemini+update" },
    { title: "Stock market rally", hot: "1M+", url: "https://www.google.com/search?q=stock+market+rally" },
    { title: "Winter storm warning", hot: "500K+", url: "https://www.google.com/search?q=winter+storm+warning" },
    { title: "Oscars nominations", hot: "500K+", url: "https://www.google.com/search?q=Oscars+nominations" },
    { title: "Electric vehicle tax credit", hot: "200K+", url: "https://www.google.com/search?q=EV+tax+credit" },
    { title: "World Cup qualifiers", hot: "200K+", url: "https://www.google.com/search?q=World+Cup+qualifiers" },
    { title: "Nobel Prize ceremony", hot: "100K+", url: "https://www.google.com/search?q=Nobel+Prize+ceremony" },
    { title: "SpaceX launch", hot: "100K+", url: "https://www.google.com/search?q=SpaceX+launch" },
    { title: "New iPhone rumors", hot: "100K+", url: "https://www.google.com/search?q=new+iPhone+rumors" },
    { title: "Climate summit", hot: "50K+", url: "https://www.google.com/search?q=climate+summit" },
    { title: "Marathon world record", hot: "50K+", url: "https://www.google.com/search?q=marathon+world+record" },
    { title: "Flu season peak", hot: "20K+", url: "https://www.google.com/search?q=flu+season" },
  ],
  reddit: [
    { title: "r/technology: OpenAI unveils new reasoning model that beats humans on math olympiad", hot: "38.2k", url: "https://www.reddit.com/search/?q=OpenAI+reasoning+model" },
    { title: "r/pics: First heavy snowfall of the season transforms this city overnight", hot: "31.7k", url: "https://www.reddit.com/search/?q=first+heavy+snowfall" },
    { title: "r/aww: Rescued dog sees snow for the first time and can't contain himself", hot: "28.4k", url: "https://www.reddit.com/search/?q=dog+sees+snow" },
    { title: "r/worldnews: Major summit reaches historic climate agreement", hot: "25.1k", url: "https://www.reddit.com/search/?q=climate+agreement" },
    { title: "r/gaming: Indie studio drops surprise demo and the internet loses its mind", hot: "22.6k", url: "https://www.reddit.com/search/?q=indie+game+demo" },
    { title: "r/AskReddit: What's the best life hack you learned from your grandparents?", hot: "19.3k", url: "https://www.reddit.com/search/?q=life+hack+grandparents" },
    { title: "r/space: Stunning new images from deep space telescope", hot: "17.8k", url: "https://www.reddit.com/search/?q=deep+space+telescope" },
    { title: "r/science: Breakthrough in solid-state battery research", hot: "15.2k", url: "https://www.reddit.com/search/?q=solid+state+battery" },
    { title: "r/movies: Trailer for the most anticipated sci-fi film of the year drops", hot: "13.9k", url: "https://www.reddit.com/search/?q=sci-fi+trailer" },
    { title: "r/DIY: Guy builds a cozy cabin for his dog, results are amazing", hot: "11.4k", url: "https://www.reddit.com/search/?q=dog+cabin+DIY" },
    { title: "r/programming: The end of the JavaScript framework wars?", hot: "9.8k", url: "https://www.reddit.com/search/?q=JavaScript+framework" },
    { title: "r/sports: Underdog team stuns champions in overtime thriller", hot: "8.2k", url: "https://www.reddit.com/search/?q=underdog+overtime" },
  ],
  hackernews: [
    { title: "Show HN: I built an open-source local-first notes app", hot: "912 分", url: "https://hn.algolia.com/?q=local-first+notes" },
    { title: "The inside story of how the SQLite team maintains the world's most deployed database", hot: "845 分", url: "https://hn.algolia.com/?q=SQLite+story" },
    { title: "Rust 2026 roadmap published", hot: "767 分", url: "https://hn.algolia.com/?q=Rust+2026+roadmap" },
    { title: "A compiler that runs entirely in the browser", hot: "698 分", url: "https://hn.algolia.com/?q=browser+compiler" },
    { title: "Why we moved our database back to Postgres", hot: "623 分", url: "https://hn.algolia.com/?q=moved+back+to+Postgres" },
    { title: "Satellites show record sea ice loss this winter", hot: "581 分", url: "https://hn.algolia.com/?q=sea+ice+loss" },
    { title: "Launch HN: New hardware startup shipping open-source e-ink tablets", hot: "534 分", url: "https://hn.algolia.com/?q=e-ink+tablet" },
    { title: "Reverse-engineering a 30-year-old game console", hot: "482 分", url: "https://hn.algolia.com/?q=reverse+engineering+console" },
    { title: "The quiet death of the personal website", hot: "431 分", url: "https://hn.algolia.com/?q=personal+website" },
    { title: "Ask HN: How do you stay focused in 2026?", hot: "396 分", url: "https://hn.algolia.com/?q=stay+focused" },
    { title: "A deep dive into Linux kernel scheduling", hot: "348 分", url: "https://hn.algolia.com/?q=kernel+scheduling" },
    { title: "PostgreSQL 18 released with major performance gains", hot: "312 分", url: "https://hn.algolia.com/?q=PostgreSQL+18" },
  ],
  twitter: [
    { title: "#CryptoRally", hot: "128万 推文", url: "https://x.com/search?q=%23CryptoRally" },
    { title: "OpenAI News", hot: "96.5万 推文", url: "https://x.com/search?q=OpenAI" },
    { title: "#MondayMotivation", hot: "74.2万 推文", url: "https://x.com/search?q=%23MondayMotivation" },
    { title: "GTA VI", hot: "68.8万 推文", url: "https://x.com/search?q=GTA+VI" },
    { title: "#WinterStorm", hot: "55.3万 推文", url: "https://x.com/search?q=%23WinterStorm" },
    { title: "SpaceX", hot: "47.9万 推文", url: "https://x.com/search?q=SpaceX" },
    { title: "#SilentQuitting", hot: "41.6万 推文", url: "https://x.com/search?q=%23SilentQuitting" },
    { title: "Messi", hot: "38.4万 推文", url: "https://x.com/search?q=Messi" },
    { title: "#AIGenerated", hot: "33.1万 推文", url: "https://x.com/search?q=%23AIGenerated" },
    { title: "Nvidia", hot: "29.7万 推文", url: "https://x.com/search?q=Nvidia" },
    { title: "#HolidaySeason", hot: "24.5万 推文", url: "https://x.com/search?q=%23HolidaySeason" },
    { title: "Tesla FSD", hot: "21.3万 推文", url: "https://x.com/search?q=Tesla+FSD" },
  ],
  youtube: [
    { title: "I Built a Snow Castle in My Backyard", hot: "1234万 次观看", url: "https://www.youtube.com/results?search_query=snow+castle" },
    { title: "Top 10 Tech Predictions for the Year", hot: "987万 次观看", url: "https://www.youtube.com/results?search_query=tech+predictions" },
    { title: "The Ultimate Winter Road Trip", hot: "854万 次观看", url: "https://www.youtube.com/results?search_query=winter+road+trip" },
    { title: "New Console Unboxing & First Impressions", hot: "762万 次观看", url: "https://www.youtube.com/results?search_query=console+unboxing" },
    { title: "Cooking Christmas Dinner Like a Chef", hot: "689万 次观看", url: "https://www.youtube.com/results?search_query=christmas+dinner" },
    { title: "AI Generated Music: Good or Bad?", hot: "612万 次观看", url: "https://www.youtube.com/results?search_query=AI+generated+music" },
    { title: "Living Off-Grid for 30 Days in Winter", hot: "545万 次观看", url: "https://www.youtube.com/results?search_query=off-grid+winter" },
    { title: "The Most Relaxing 4K Snowfall Video", hot: "478万 次观看", url: "https://www.youtube.com/results?search_query=4K+snowfall" },
    { title: "Ultimate Ski Trick Compilation", hot: "421万 次观看", url: "https://www.youtube.com/results?search_query=ski+tricks" },
    { title: "We Tested the World's Fastest RC Car", hot: "365万 次观看", url: "https://www.youtube.com/results?search_query=fastest+RC+car" },
    { title: "24 Hours in a 5-Star Hotel vs 1-Star", hot: "312万 次观看", url: "https://www.youtube.com/results?search_query=hotel+comparison" },
    { title: "How Smartphones Are Made (Factory Tour)", hot: "276万 次观看", url: "https://www.youtube.com/results?search_query=smartphone+factory" },
  ],
};
