import type { HotItem, PlatformKey } from "./types";

/**
 * 演示数据：当实时接口不可用时兜底展示，保证页面始终有内容。
 * url 均指向对应平台的搜索结果页。
 */
export const FALLBACK: Record<PlatformKey, HotItem[]> = {
  baidu: [
    { title: "国产大模型发布新一代多模态版本", hot: "1435万", url: "https://www.baidu.com/s?wd=国产大模型新版" },
    { title: "春节档电影票房刷新影史纪录", hot: "1288万", url: "https://www.baidu.com/s?wd=春节档电影票房" },
    { title: "多地迎来今冬最强降雪天气", hot: "1021万", url: "https://www.baidu.com/s?wd=今冬最强降雪" },
    { title: "新能源车冬季续航实测公布", hot: "864万", url: "https://www.baidu.com/s?wd=新能源车冬季续航" },
    { title: "春晚节目单首次联排曝光", hot: "798万", url: "https://www.baidu.com/s?wd=春晚节目单" },
    { title: "年轻人流行起'反向消费'新潮流", hot: "663万", url: "https://www.baidu.com/s?wd=反向消费" },
    { title: "新款折叠屏手机开售引发抢购", hot: "592万", url: "https://www.baidu.com/s?wd=新款折叠屏手机" },
    { title: "文旅部公布冬季冰雪游热门城市", hot: "501万", url: "https://www.baidu.com/s?wd=冬季冰雪游热门城市" },
    { title: "国产科幻电影启动全球发行", hot: "468万", url: "https://www.baidu.com/s?wd=国产科幻电影" },
    { title: "春运首日火车票今日开售", hot: "432万", url: "https://www.baidu.com/s?wd=春运火车票开售" },
    { title: "知名游戏厂商宣布新作定档", hot: "389万", url: "https://www.baidu.com/s?wd=游戏新作定档" },
    { title: "医保谈判结果公布多款新药入保", hot: "355万", url: "https://www.baidu.com/s?wd=医保谈判结果" },
  ],
  weibo: [
    { title: "顶流官宣恋情引爆热搜", hot: "1023万", url: "https://s.weibo.com/weibo?q=官宣恋情" },
    { title: "考研成绩今日公布", hot: "876万", url: "https://s.weibo.com/weibo?q=考研成绩公布" },
    { title: "哈尔滨冰雪大世界正式开园", hot: "742万", url: "https://s.weibo.com/weibo?q=哈尔滨冰雪大世界" },
    { title: "某热播剧大结局观众意难平", hot: "698万", url: "https://s.weibo.com/weibo?q=热播剧大结局" },
    { title: "演唱会门票二次开售秒空", hot: "613万", url: "https://s.weibo.com/weibo?q=演唱会门票" },
    { title: "明星回应争议事件", hot: "566万", url: "https://s.weibo.com/weibo?q=明星回应争议" },
    { title: "新综艺阵容官宣", hot: "501万", url: "https://s.weibo.com/weibo?q=新综艺阵容" },
    { title: "网友晒出自家雪人创意大赛", hot: "447万", url: "https://s.weibo.com/weibo?q=堆雪人大赛" },
    { title: "跨年晚会官宣首批嘉宾", hot: "389万", url: "https://s.weibo.com/weibo?q=跨年晚会嘉宾" },
    { title: "宠物橘猫表情包走红网络", hot: "302万", url: "https://s.weibo.com/weibo?q=橘猫表情包" },
    { title: "专家解读呼吸道疾病高发季", hot: "271万", url: "https://s.weibo.com/weibo?q=呼吸道疾病" },
    { title: "00后整顿职场新话题", hot: "238万", url: "https://s.weibo.com/weibo?q=00后整顿职场" },
  ],
  bilibili: [
    { title: "年度百大UP主评选结果揭晓", hot: "89万+", url: "https://search.bilibili.com/all?keyword=百大UP主" },
    { title: "新番开播首集口碑炸裂", hot: "76万+", url: "https://search.bilibili.com/all?keyword=新番开播" },
    { title: "国产独立游戏发布实机演示", hot: "68万+", url: "https://search.bilibili.com/all?keyword=独立游戏实机" },
    { title: "手工耿新发明上线", hot: "59万+", url: "https://search.bilibili.com/all?keyword=手工耿" },
    { title: "冰上运动合集播放量破亿", hot: "47万+", url: "https://search.bilibili.com/all?keyword=冰上运动" },
    { title: "鬼畜区年度金曲盘点", hot: "41万+", url: "https://search.bilibili.com/all?keyword=鬼畜金曲" },
    { title: "新人UP主一周涨粉百万", hot: "36万+", url: "https://search.bilibili.com/all?keyword=新人UP主" },
    { title: "纪录片《雪原》上线", hot: "31万+", url: "https://search.bilibili.com/all?keyword=雪原纪录片" },
    { title: "游戏新春版本更新预告", hot: "28万+", url: "https://search.bilibili.com/all?keyword=游戏新春版本" },
    { title: "科技区大佬拆解新款芯片", hot: "24万+", url: "https://search.bilibili.com/all?keyword=拆解芯片" },
    { title: "跨年晚会舞台cut合集", hot: "19万+", url: "https://search.bilibili.com/all?keyword=跨年舞台" },
    { title: "虚拟主播演唱会回放", hot: "15万+", url: "https://search.bilibili.com/all?keyword=虚拟主播演唱会" },
  ],
  zhihu: [
    { title: "如何评价新发布的多模态大模型？", hot: "1280万热度", url: "https://www.zhihu.com/search?type=content&q=多模态大模型" },
    { title: "为什么年轻人开始过'无消费周末'？", hot: "986万热度", url: "https://www.zhihu.com/search?type=content&q=无消费周朒" },
    { title: "东北旅游爆火背后的原因是什么？", hot: "872万热度", url: "https://www.zhihu.com/search?type=content&q=东北旅游爆火" },
    { title: "考研失败后如何规划人生？", hot: "754万热度", url: "https://www.zhihu.com/search?type=content&q=考研失败人生规划" },
    { title: "如何看待新能源车冬季续航打折？", hot: "689万热度", url: "https://www.zhihu.com/search?type=content&q=新能源车续航" },
    { title: "普通人如何抓住AI浪潮？", hot: "611万热度", url: "https://www.zhihu.com/search?type=content&q=普通人AI浪潮" },
    { title: "有哪些值得推荐的冬季旅行地？", hot: "532万热度", url: "https://www.zhihu.com/search?type=content&q=冬季旅行地" },
    { title: "为什么电影院春节档年年爆满？", hot: "477万热度", url: "https://www.zhihu.com/search?type=content&q=春节档电影" },
    { title: "大城市的通勤幸福感从何而来？", hot: "399万热度", url: "https://www.zhihu.com/search?type=content&q=通勤幸福感" },
    { title: "如何看待'反向留学'现象？", hot: "345万热度", url: "https://www.zhihu.com/search?type=content&q=反向留学" },
    { title: "编程入门学哪门语言最合适？", hot: "312万热度", url: "https://www.zhihu.com/search?type=content&q=编程入门语言" },
    { title: "为什么南方冬天比北方更冷？", hot: "276万热度", url: "https://www.zhihu.com/search?type=content&q=南方冬天更冷" },
  ],
  douyin: [
    { title: "#冰雪变装挑战", hot: "1568万", url: "https://www.douyin.com/search/冰雪变装挑战" },
    { title: "#城市冬日漫游指南", hot: "1211万", url: "https://www.douyin.com/search/城市冬日漫游" },
    { title: "#一人食火锅新吃法", hot: "986万", url: "https://www.douyin.com/search/一人食火锅" },
    { title: "#AI写真火了", hot: "874万", url: "https://www.douyin.com/search/AI写真" },
    { title: "#宠物第一视角vlog", hot: "762万", url: "https://www.douyin.com/search/宠物第一视角" },
    { title: "#滑雪新手教程", hot: "655万", url: "https://www.douyin.com/search/滑雪新手教程" },
    { title: "#跨年烟花夜拍", hot: "578万", url: "https://www.douyin.com/search/跨年烟花" },
    { title: "#街头偶遇随机搭子", hot: "489万", url: "https://www.douyin.com/search/街头偶遇" },
    { title: "#北方冬天的快乐", hot: "402万", url: "https://www.douyin.com/search/北方冬天" },
    { title: "#收纳整理新思路", hot: "366万", url: "https://www.douyin.com/search/收纳整理" },
    { title: "#幼儿园可爱瞬间", hot: "318万", url: "https://www.douyin.com/search/幼儿园可爱瞬间" },
    { title: "#考研上岸vlog", hot: "274万", url: "https://www.douyin.com/search/考研上岸" },
  ],
  google: [
    { title: "Gemini update", hot: "2M+", url: "https://www.google.com/search?q=Gemini+update" },
    { title: "Stock market rally", hot: "1M+", url: "https://www.google.com/search?q=stock+market+rally" },
    { title: "Winter storm warning", hot: "500K+", url: "https://www.google.com/search?q=winter+storm+warning" },
    { title: "Oscars nominations", hot: "500K+", url: "https://www.google.com/search?q=Oscars+nominations" },
    { title: "Electric vehicle tax credit", hot: "200K+", url: "https://www.google.com/search?q=EV+tax+credit" },
    { title: "World Cup qualifiers", hot: "200K+", url: "https://www.google.com/search?q=World+Cup+qualifiers" },
    { title: "Nobel Prize ceremony", hot: "100K+", url: "https://www.google.com/search?q=Nobel+Prize+ceremony" },
    { title: "SpaceX launch", hot: "100K+", url: "https://www.google.com/search?q=SpaceX+launch" },
    { title: "New iPhone rumors", hot: "100K+", url: "https://www.google.com/search?q=new+iPhone+rumors" },
    { title: "Climate summit", hot: "50K+", url: "https://www.google.com/search?q=climate+summit" },
    { title: "Marathon world record", hot: "50K+", url: "https://www.google.com/search?q=marathon+world+record" },
    { title: "Flu season peak", hot: "20K+", url: "https://www.google.com/search?q=flu+season" },
  ],
  reddit: [
    { title: "r/technology: OpenAI unveils new reasoning model that beats humans on math olympiad", hot: "38.2k", url: "https://www.reddit.com/search/?q=OpenAI+reasoning+model" },
    { title: "r/pics: First heavy snowfall of the season transforms this city overnight", hot: "31.7k", url: "https://www.reddit.com/search/?q=first+heavy+snowfall" },
    { title: "r/aww: Rescued dog sees snow for the first time and can't contain himself", hot: "28.4k", url: "https://www.reddit.com/search/?q=dog+sees+snow" },
    { title: "r/worldnews: Major summit reaches historic climate agreement", hot: "25.1k", url: "https://www.reddit.com/search/?q=climate+agreement" },
    { title: "r/gaming: Indie studio drops surprise demo and the internet loses its mind", hot: "22.6k", url: "https://www.reddit.com/search/?q=indie+game+demo" },
    { title: "r/AskReddit: What's the best life hack you learned from your grandparents?", hot: "19.3k", url: "https://www.reddit.com/search/?q=life+hack+grandparents" },
    { title: "r/space: Stunning new images from deep space telescope", hot: "17.8k", url: "https://www.reddit.com/search/?q=deep+space+telescope" },
    { title: "r/science: Breakthrough in solid-state battery research", hot: "15.2k", url: "https://www.reddit.com/search/?q=solid+state+battery" },
    { title: "r/movies: Trailer for the most anticipated sci-fi film of the year drops", hot: "13.9k", url: "https://www.reddit.com/search/?q=sci-fi+trailer" },
    { title: "r/DIY: Guy builds a cozy cabin for his dog, results are amazing", hot: "11.4k", url: "https://www.reddit.com/search/?q=dog+cabin+DIY" },
    { title: "r/programming: The end of the JavaScript framework wars?", hot: "9.8k", url: "https://www.reddit.com/search/?q=JavaScript+framework" },
    { title: "r/sports: Underdog team stuns champions in overtime thriller", hot: "8.2k", url: "https://www.reddit.com/search/?q=underdog+overtime" },
  ],
  hackernews: [
    { title: "Show HN: I built an open-source local-first notes app", hot: "912 分", url: "https://hn.algolia.com/?q=local-first+notes" },
    { title: "The inside story of how the SQLite team maintains the world's most deployed database", hot: "845 分", url: "https://hn.algolia.com/?q=SQLite+story" },
    { title: "Rust 2026 roadmap published", hot: "767 分", url: "https://hn.algolia.com/?q=Rust+2026+roadmap" },
    { title: "A compiler that runs entirely in the browser", hot: "698 分", url: "https://hn.algolia.com/?q=browser+compiler" },
    { title: "Why we moved our database back to Postgres", hot: "623 分", url: "https://hn.algolia.com/?q=moved+back+to+Postgres" },
    { title: "Satellites show record sea ice loss this winter", hot: "581 分", url: "https://hn.algolia.com/?q=sea+ice+loss" },
    { title: "Launch HN: New hardware startup shipping open-source e-ink tablets", hot: "534 分", url: "https://hn.algolia.com/?q=e-ink+tablet" },
    { title: "Reverse-engineering a 30-year-old game console", hot: "482 分", url: "https://hn.algolia.com/?q=reverse+engineering+console" },
    { title: "The quiet death of the personal website", hot: "431 分", url: "https://hn.algolia.com/?q=personal+website" },
    { title: "Ask HN: How do you stay focused in 2026?", hot: "396 分", url: "https://hn.algolia.com/?q=stay+focused" },
    { title: "A deep dive into Linux kernel scheduling", hot: "348 分", url: "https://hn.algolia.com/?q=kernel+scheduling" },
    { title: "PostgreSQL 18 released with major performance gains", hot: "312 分", url: "https://hn.algolia.com/?q=PostgreSQL+18" },
  ],
  twitter: [
    { title: "#CryptoRally", hot: "128万 推文", url: "https://x.com/search?q=%23CryptoRally" },
    { title: "OpenAI News", hot: "96.5万 推文", url: "https://x.com/search?q=OpenAI" },
    { title: "#MondayMotivation", hot: "74.2万 推文", url: "https://x.com/search?q=%23MondayMotivation" },
    { title: "GTA VI", hot: "68.8万 推文", url: "https://x.com/search?q=GTA+VI" },
    { title: "#WinterStorm", hot: "55.3万 推文", url: "https://x.com/search?q=%23WinterStorm" },
    { title: "SpaceX", hot: "47.9万 推文", url: "https://x.com/search?q=SpaceX" },
    { title: "#SilentQuitting", hot: "41.6万 推文", url: "https://x.com/search?q=%23SilentQuitting" },
    { title: "Messi", hot: "38.4万 推文", url: "https://x.com/search?q=Messi" },
    { title: "#AIGenerated", hot: "33.1万 推文", url: "https://x.com/search?q=%23AIGenerated" },
    { title: "Nvidia", hot: "29.7万 推文", url: "https://x.com/search?q=Nvidia" },
    { title: "#HolidaySeason", hot: "24.5万 推文", url: "https://x.com/search?q=%23HolidaySeason" },
    { title: "Tesla FSD", hot: "21.3万 推文", url: "https://x.com/search?q=Tesla+FSD" },
  ],
  youtube: [
    { title: "I Built a Snow Castle in My Backyard", hot: "1234万 次观看", url: "https://www.youtube.com/results?search_query=snow+castle" },
    { title: "Top 10 Tech Predictions for the Year", hot: "987万 次观看", url: "https://www.youtube.com/results?search_query=tech+predictions" },
    { title: "The Ultimate Winter Road Trip", hot: "854万 次观看", url: "https://www.youtube.com/results?search_query=winter+road+trip" },
    { title: "New Console Unboxing & First Impressions", hot: "762万 次观看", url: "https://www.youtube.com/results?search_query=console+unboxing" },
    { title: "Cooking Christmas Dinner Like a Chef", hot: "689万 次观看", url: "https://www.youtube.com/results?search_query=christmas+dinner" },
    { title: "AI Generated Music: Good or Bad?", hot: "612万 次观看", url: "https://www.youtube.com/results?search_query=AI+generated+music" },
    { title: "Living Off-Grid for 30 Days in Winter", hot: "545万 次观看", url: "https://www.youtube.com/results?search_query=off-grid+winter" },
    { title: "The Most Relaxing 4K Snowfall Video", hot: "478万 次观看", url: "https://www.youtube.com/results?search_query=4K+snowfall" },
    { title: "Ultimate Ski Trick Compilation", hot: "421万 次观看", url: "https://www.youtube.com/results?search_query=ski+tricks" },
    { title: "We Tested the World's Fastest RC Car", hot: "365万 次观看", url: "https://www.youtube.com/results?search_query=fastest+RC+car" },
    { title: "24 Hours in a 5-Star Hotel vs 1-Star", hot: "312万 次观看", url: "https://www.youtube.com/results?search_query=hotel+comparison" },
    { title: "How Smartphones Are Made (Factory Tour)", hot: "276万 次观看", url: "https://www.youtube.com/results?search_query=smartphone+factory" },
  ],
};
